In [0]:

cases = spark.read.load("/FileStore/tables/world.csv",format="csv", sep=",", inferSchema="true", header="true")

In [0]:
cases.show()

+---+-------+---+------+-------------+--------+
|_c0|user_id|age|gender|   occupation|zip_code|
+---+-------+---+------+-------------+--------+
|  0|      1| 24|     M|   technician|   85711|
|  1|      2| 53|     F|        other|   94043|
|  2|      3| 23|     M|       writer|   32067|
|  3|      4| 24|     M|   technician|   43537|
|  4|      5| 33|     F|        other|   15213|
|  5|      6| 42|     M|    executive|   98101|
|  6|      7| 57|     M|administrator|   91344|
|  7|      8| 36|     M|administrator|   05201|
|  8|      9| 29|     M|      student|   01002|
|  9|     10| 53|     M|       lawyer|   90703|
| 10|     11| 39|     F|        other|   30329|
| 11|     12| 28|     F|        other|   06405|
| 12|     13| 47|     M|     educator|   29206|
| 13|     14| 45|     M|    scientist|   55106|
| 14|     15| 49|     F|     educator|   97301|
| 15|     16| 21|     M|entertainment|   10309|
| 16|     17| 30|     M|   programmer|   06355|
| 17|     18| 35|     F|        other|   37212|
| 18|     19| 40|     M|    librarian|   02138|
| 19|     20| 42|     F|    homemaker|   95660|
+---+-------+---+------+-------------+--------+
only showing top 20 rows

In [0]:
cases.head(4)

Out[4]: [Row(_c0=0, user_id=1, age=24, gender='M', occupation='technician', zip_code='85711'),
 Row(_c0=1, user_id=2, age=53, gender='F', occupation='other', zip_code='94043'),
 Row(_c0=2, user_id=3, age=23, gender='M', occupation='writer', zip_code='32067'),
 Row(_c0=3, user_id=4, age=24, gender='M', occupation='technician', zip_code='43537')]

In [0]:
cases.tail(5)

Out[5]: [Row(_c0=939, user_id=940, age=32, gender='M', occupation='administrator', zip_code='02215'),
 Row(_c0=940, user_id=941, age=20, gender='M', occupation='student', zip_code='97229'),
 Row(_c0=941, user_id=942, age=48, gender='F', occupation='librarian', zip_code='78209'),
 Row(_c0=942, user_id=943, age=22, gender='M', occupation='student', zip_code='77841'),
 Row(_c0=943, user_id=944, age=22, gender='M', occupation=None, zip_code='77841')]

In [0]:
cases1 = cases.withColumnRenamed("user_id","id")
cases1.show()

+---+---+---+------+-------------+--------+
|_c0| id|age|gender|   occupation|zip_code|
+---+---+---+------+-------------+--------+
|  0|  1| 24|     M|   technician|   85711|
|  1|  2| 53|     F|        other|   94043|
|  2|  3| 23|     M|       writer|   32067|
|  3|  4| 24|     M|   technician|   43537|
|  4|  5| 33|     F|        other|   15213|
|  5|  6| 42|     M|    executive|   98101|
|  6|  7| 57|     M|administrator|   91344|
|  7|  8| 36|     M|administrator|   05201|
|  8|  9| 29|     M|      student|   01002|
|  9| 10| 53|     M|       lawyer|   90703|
| 10| 11| 39|     F|        other|   30329|
| 11| 12| 28|     F|        other|   06405|
| 12| 13| 47|     M|     educator|   29206|
| 13| 14| 45|     M|    scientist|   55106|
| 14| 15| 49|     F|     educator|   97301|
| 15| 16| 21|     M|entertainment|   10309|
| 16| 17| 30|     M|   programmer|   06355|
| 17| 18| 35|     F|        other|   37212|
| 18| 19| 40|     M|    librarian|   02138|
| 19| 20| 42|     F|    homemaker|   95660|
+---+---+---+------+-------------+--------+
only showing top 20 rows

In [0]:
cases1.filter((cases1.age>20) & (cases1.gender=='M')).show()

+---+---+---+------+-------------+--------+
|_c0| id|age|gender|   occupation|zip_code|
+---+---+---+------+-------------+--------+
|  0|  1| 24|     M|   technician|   85711|
|  2|  3| 23|     M|       writer|   32067|
|  3|  4| 24|     M|   technician|   43537|
|  5|  6| 42|     M|    executive|   98101|
|  6|  7| 57|     M|administrator|   91344|
|  7|  8| 36|     M|administrator|   05201|
|  8|  9| 29|     M|      student|   01002|
|  9| 10| 53|     M|       lawyer|   90703|
| 12| 13| 47|     M|     educator|   29206|
| 13| 14| 45|     M|    scientist|   55106|
| 15| 16| 21|     M|entertainment|   10309|
| 16| 17| 30|     M|   programmer|   06355|
| 18| 19| 40|     M|    librarian|   02138|
| 20| 21| 26|     M|       writer|   30068|
| 21| 22| 25|     M|       writer|   40206|
| 24| 25| 39|     M|     engineer|   55107|
| 25| 26| 49|     M|     engineer|   21044|
| 27| 28| 32|     M|       writer|   55369|
| 28| 29| 41|     M|   programmer|   94043|
| 30| 31| 24|     M|       artist|   10003|
+---+---+---+------+-------------+--------+
only showing top 20 rows

In [0]:
from pyspark.sql import functions as F
cases.groupBy(["Age","gender"]).agg(F.sum("zip_code") ,F.max("zip_code")).show()

+---+------+-------------+-------------+
|Age|gender|sum(zip_code)|max(zip_code)|
+---+------+-------------+-------------+
|  7|     M|      55436.0|        55436|
| 10|     M|      77459.0|        77459|
| 11|     M|      94619.0|        94619|
| 13|     F|     110443.0|        55337|
| 13|     M|     226126.0|        94306|
| 14|     F|      82500.0|        53115|
| 15|     F|      75923.0|        44212|
| 15|     M|     124003.0|        98102|
| 16|     F|     145158.0|        95453|
| 16|     M|     150417.0|        84010|
| 17|     F|     156728.0|        61073|
| 17|     M|     671348.0|        97302|
| 18|     F|     650176.0|        98620|
| 18|     M|     426380.0|        97520|
| 19|     F|     558073.0|        99687|
| 19|     M|     710076.0|        93612|
| 20|     F|     526672.0|        98801|
| 20|     M|    1132385.0|        99835|
| 21|     F|     317239.0|        94533|
| 21|     M|    1078648.0|        N4T1A|
+---+------+-------------+-------------+
only showing top 20 rows